name: Fly Deploy
on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'sanity/**'
      - 'package*.json'
      - 'next.config.js'
      - 'tailwind.config.ts'
      - 'tsconfig.json'
      - 'postcss.config.js'
      - 'eslint.config.js'
      - 'Dockerfile*'
      - 'sanity.cli.ts'
      - 'sanity.config.ts'
      - 'fly.toml'
      - '.env.local.example'
      - '.github/**'
jobs:
  lint:
    name: Lint & Type Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Run TypeScript type check
        run: npm run type-check

      - name: Check code formatting
        run: npx prettier --check .

  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    needs: lint
    environment: prod
    concurrency: deploy-group # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@v1
      - run: flyctl console --dockerfile Dockerfile.builder -C "/srv/deploy.sh" --env=FLY_API_TOKEN="$FLY_API_TOKEN"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
